got_accueil:
    path:     /accueil
    defaults: { _controller: omggotBundle:Personnage:accueil }

got_fiche_perso:
    path:     /personnage/{id}
    defaults: { _controller: omggotBundle:Personnage:personnage }

got_ajouter:
    path:     /ajouter
    defaults: { _controller: omggotBundle:Personnage:ajouter }

got_rechercher:
    path:     /rechercher
    defaults: { _controller: omggotBundle:Personnage:rechercher }

got_success:
    path:     /success
    defaults: { _controller: omggotBundle:Personnage:success }

got_liste_comp:
    path:     /liste_comp
    defaults: { _controller: omggotBundle:Competences:liste }

got_comp:
    path:     /comp/{id}
    defaults: { _controller: omggotBundle:Competences:comp }

got_ajouter_comp:
    path:     /ajouter_comp
    defaults: { _controller: omggotBundle:Competences:ajouter }


