omggot_accueil:
    path:     /accueil
    defaults: { _controller: omggotBundle:Default:accueil }

omggot_ajouter:
    path:     /ajouter
    defaults: { _controller: omggotBundle:Default:ajouter }

omggot_rechercher:
    path:    /rechercher
    defaults: { _controller: omggotBundle:Default:rechercher }
