got_accueil:
    path:     /accueil
    defaults: { _controller: omggotBundle:Personnage:accueil }

got_ajouter:
    path:     /ajouter
    defaults: { _controller: omggotBundle:Personnage:ajouter }

got_rechercher:
    path:     /rechercher
    defaults: { _controller: omggotBundle:Personnage:rechercher }

got_success:
    path:     /success
    defaults: { _controller: omggotBundle:Personnage:success }
